// src/vue/App.vue
<template>
  <div class="container">
    <h1>Vue Page</h1>
    <div class="content">
      <p>This is the Vue implementation using TypeScript.</p>
      <p>This page is served independently and doesn't load React or native JS assets.</p>
      <p>Testing edits from nvim</p>
    </div>
    <div class="back-link">
      <a href="/">← Back to Home</a>
    </div>
  </div>
</template>

<script setup lang="ts">
// Vue 3 Composition API with TypeScript
console.log('test')
</script>

<style scoped>
.container {
  padding: 2rem;
  max-width: 800px;
  margin: 0 auto;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
  margin-top: 2rem;
}

h1 {
  color: #333;
  text-align: center;
  margin-bottom: 2rem;
}

.content {
  margin-bottom: 2rem;
}

.back-link {
  text-align: center;
}

.back-link a {
  display: inline-block;
  padding: 0.75rem 1.5rem;
  background: #4fc08d;
  color: white;
  text-decoration: none;
  border-radius: 6px;
  font-weight: 500;
}

.back-link a:hover {
  background: #3a9068;
}
</style>

// data-table-play/src/react/App.tsx
import React from 'react'

const App: React.FC = () => {
  return (
    <div style={{ 
      padding: '2rem', 
      maxWidth: '800px', 
      margin: '0 auto',
      background: 'white',
      borderRadius: '8px',
      boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
      marginTop: '2rem'
    }}>
      <h1 style={{ 
        color: '#333', 
        textAlign: 'center',
        marginBottom: '2rem'
      }}>
        React Page
      </h1>
      <div style={{ marginBottom: '2rem' }}>
        <p>This is the React implementation using TypeScript.</p>
        <p>This page is served independently and doesn't load Vue or native JS assets.</p>
      </div>
      <div style={{ textAlign: 'center' }}>
        <a 
          href="/" 
          style={{
            display: 'inline-block',
            padding: '0.75rem 1.5rem',
            background: '#61dafb',
            color: 'white',
            textDecoration: 'none',
            borderRadius: '6px',
            fontWeight: '500'
          }}
        >
          ← Back to Home
        </a>
      </div>
    </div>
  )
}

export default App
